import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'




// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://www.expandtheroom.com/wp-json/wp/v2/posts?per_page=20??page=2`)
  const posts = await res.json()

 
  // Pass data to the page via props
  return { props: { posts } }

}

export default function Home({posts}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://www.expandtheroom.com/">ETR</a> Posts 
        </h1>
   
        <div className={styles.grid}>
          {posts?.map(({title, id, slug}) => {
            return (
              // eslint-disable-next-line react/jsx-key
              <div  key={id} className={styles.card}>
                <Link
                 href={`post/${slug}`}>{title.rendered}
                </Link>
              </div>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        
      </footer>
    </div>
  )
}
